# Configurations
title:            MLNLP-MuLi-Notes
longtitle:        MLNLP-MuLi-Notes
author:           Aleafy
email:            1015014322@qq.com
description: >
  MLNLP社区推出的李沐老师《动手学深度学习》课程笔记与代码。

version:          1.0
gitbook_version:  3.2.3

url:              'https://aleafy.github.io'
baseurl:          '/jekyll-gitbook'
rss:              RSS

toc:
  enabled: true
  h_min: 1
  h_max: 75

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jemoji
